import cloudinary from "../config/cloudinary"

// uploads image to cloudinary as webp with given width and height, returns webp url and public id
const uploadImage = async (image, directory, productId, width = 1000, height = 1000) => {
  const uploadOptions = {
    folder: `ecom-app/${directory}-${productId}`,
    resource_type: "image",
    eager: [
      {
        width: width,
        height: height,
        crop: "fill",
        quality: "auto",
        format: "webp",
      },
    ],
  }

  const result = await cloudinary.uploader.upload(image, uploadOptions)

  return {
    // returns the secure webp url generated by eager transformation
    secure_url: result.eager?.[0]?.secure_url || result.secure_url,
    public_id: result.public_id,
  }
}

export default uploadImage
